import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const js = fs.readFileSync(new URL('../assets/product-parity-demo.js', import.meta.url), 'utf8');
const css = fs.readFileSync(new URL('../assets/product-parity-demo.css', import.meta.url), 'utf8');
assert.doesNotThrow(() => new vm.Script(js));
const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size, ids.length, 'duplicate IDs');
for(const required of ['main','result','pending-state','confirm-decision','completion-pending','completion-state','hub-pending','hub-state','complete-owner','hub-owner']) assert.ok(ids.includes(required), `missing ${required}`);
for(const n of ['1','2','3','4','5','6']) assert.match(html, new RegExp(`<span>${n}<\\/span>`));
assert.match(js, /selectOwner/);assert.match(js,/confirmDecision/);assert.match(js,/confirmed: false/);assert.match(js,/confirmed: true/);
assert.match(css, /@media\(max-width:900px\)/);assert.match(css, /@media\(max-width:420px\)/);
console.log('Yberium Demo recovery smoke checks passed.');
